### ISSUE TITLE
[Feature request] Decouple metrics collection from /metrics endpoint

### ISSUE THREAD

**Issue by kremers** [pryorda/vmware_exporter#107]
Metrics collection can take various amounts of time, for my instance for example (about 64.000 rows metrics output) the exporter takes about 21 seconds to collect all data.

Since Prometheus uses 1min scrape duration defaults (1), Kubernetes Liveness and readyness probes might put load on the endpoint as well, especially since the defaults (2) (periodSeconds 10sec, timeout 1sec) will not work properly.

The following things can be implemented to solve the issue:
- Async metrics collection in a fine tunable interval from command line arguments or env variable & /metrics endpoint showing the latest data with some TTL, so no outdated data will be shown
- Health endpoint responding if metrics collection was successfull and the cached data are still in the TTL

Major benefits:
- The exporter can not be used to D/DOS the VCenter API
- Queries will be way faster if the data has been collected in advance
- Health collection does not require metrics overhead
- Exporter will fit seamlessly into the K8S defaults, even the tight scrape interval defaults of Prometheus will work without hazzle

[1] https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cduration%3E
[2] https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

**Comment by dannyk81** [comment]
Hey @kremers!

Interesting feedback, my 2 cents:

1) async metrics collection is indeed possible and has some advantages, however is generally not the best practice [1], possible alternatives would be to:
 a) run multiple exporters, each responsible for a subset of the collectors
 b) consider supporting URL params for specifying the collectors during scrape, this way multiple scrape targets (black-exporter style) could be specified for each collector thus splitting the scrape to smaller portions.

2) Health endpoint should have very simple logic, mainly covering scenarios of application dead-locks, if there's an issue (error, timeouts, etc..) with metrics collection that should be returned with the scrape response (which indeed makes it more difficult with metrics are collected in an async way, and is generally why it's discouraged), which will provide the necessary input (in a form of "not up") to flag that there's an issue with metrics collection without unnecessarily killing/restarting the exporter.


[1] https://prometheus.io/docs/instrumenting/writing_exporters/#scheduling

**Comment by Jc2k** [comment]
Fully agree with @dannyk81. Don't think liveness/health checks should be putting load on the system. Async collection has been a PITA for me with other exporters and wold definitely want to stick with with official prometheus guidelines.

We probably could do something where multiple concurrent requests for the same data were done once and shared between requests but thats probably not a common problem (under the hood this would be a bit like a variation of the run_once_property primitive).

**Comment by kremers** [comment]
@dannyk81 thank you for mentioning the scheduling part. 

> If a metric is particularly expensive to retrieve, i.e. takes more than a minute, it is acceptable to cache it. This should be noted in the HELP string.
> 
> The default scrape timeout for Prometheus is 10 seconds. If your exporter can be expected to exceed this, you should explicitly call this out in your user documentation.

Depending on the vcenter size scrapes would take more than 10 seconds for sure. So we should put this into the docs?

Standard prometheus exporters expect to expose metrics from systems directly which is mostly cheap instead of calling external APIs to gather metrics. @Jc2k suggestion would solve the issue of possible DDOS the API through the exporter, at least for bigger queries.
