### ISSUE TITLE
Multiple idling sessions from exporter in VC

### ISSUE THREAD

**Issue by NosIreland** [pryorda/vmware_exporter#109]
Hi,
I use exporter to collect metrics from Vcenter. 
On Vcenter monitor/sessions I noticed many(~30) idling sessions from exporter. Any reason why the sessions are not closed by exporter?

**Comment by kremers** [comment]
Can you provide a screenshot?
Do you see the connection timestamps?

Trying to figure out if no connection is closed or just some are left idling

**Comment by Jc2k** [comment]
At a guess i would say theres is a typo on [this line](https://github.com/pryorda/vmware_exporter/blob/master/vmware_exporter/vmware_exporter.py#L215). Where are the `()` hiding? If memory serves twisted inline callbacks assume non deferreds should be treated as a deferred that has already fired, so this probably just carries on executing without calling disconnect.

**Comment by NosIreland** [comment]
> 
> 
> Can you provide a screenshot?
> Do you see the connection timestamps?
> 
> Trying to figure out if no connection is closed or just some are left idling

See screenshot below:

**Comment by NosIreland** [comment]
> 
> 
> At a guess i would say theres is a typo on [this line](https://github.com/pryorda/vmware_exporter/blob/master/vmware_exporter/vmware_exporter.py#L215). Where are the `()` hiding? If memory serves twisted inline callbacks assume non deferreds should be treated as a deferred that has already fired, so this probably just carries on executing without calling disconnect.

Looks like this was it. I've modified the code and built my own image and I do not see any more idling session. I'll test it overnight just to be sure.

**Comment by dannyk81** [comment]
cool! @NosIreland care to submit a PR?

**Comment by NosIreland** [comment]
Can confirm that after almost 24hours all looking good none of  my Vcenter have idling sessions anymore.
