### ISSUE TITLE
vmware_host_boot_timestamp_seconds

### ISSUE THREAD

**Issue by adityavijjanT** [pryorda/vmware_exporter#110]
I have checked this value is not matching with ESXi boot time.. I have divided value in seconds by 86400 to convert to days, but the value i am getting is too high.

Is there any specific math to calculate the correct value.

**Comment by dannyk81** [comment]
The value of this metric is the time in Epoch format when the server booted.

if you want to calculate the uptime (in days for example) you can use this query:
```
(time() - vmware_host_boot_timestamp_seconds) / 86400
```

for example:
```

{cluster_name="XXX",dc_name="YYY",host_name="esx-pre-1.example.com",instance="vcenter",job="vmware-exporter"} | 381.08698010930584

[root@esx-pre-1:~] uptime
 20:46:47 up 381 days, 02:05:21, load average: 0.42, 0.46, 0.46
```

hope that clarifies things.

**Comment by adityavijjanT** [comment]
Thanks for the quick response ! 

Yes this works with data-source as Prometheus in Grafana, I am using Influxdb as data-source and the values are diff.

Below is query used for Influxdb - 

SELECT last("value")  / 86400 FROM "vmware_host_boot_timestamp_seconds" WHERE ("host_name" = 'test.test.local') AND $timeFilter GROUP BY time($interval) fill(null)

**Comment by pryorda** [comment]
@adityavijjanT Are we good to close this out then?

**Comment by adityavijjanT** [comment]
Yes we can close as values are correct in Prometheus, will check how to convert this in correct values from influxdb.
