### ISSUE TITLE
NFS VM's

### ISSUE THREAD

**Issue by cukal** [pryorda/vmware_exporter#116]
ESXi 6.0.0 Update 3 (Build 7504637) and vmware_exporter docker image. 

Metrics ```vmware_vm_disk_*_average``` only includes VM's stored on a local datastore.  
VM's stored on an NFS volume are missing from the metric output.

**Comment by pryorda** [comment]
What version are you running?

**Comment by cukal** [comment]
Thanks for you reply and the exporter! 

Tested with v0.9.1

```
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
pryorda/vmware_exporter   latest              8238d3efc5ee        8 days ago          141MB
```

I just noticed this as we're starting to use VM's on NFS & still using v0.1.2 (Python install from way before) and never upgraded but it's the same with docker image v0.9.1.
We're not using vCenter fyi.

**Comment by pryorda** [comment]
Interesting. I now need to validate this is still okay on iscsi. I'm willing to bet they expose some other metric for nfs :/

**Comment by pryorda** [comment]
https://www.vmware.com/support/developer/converter-sdk/conv61_apireference/virtual_disk_counters.html For reference here. I need to look closer at this.

**Comment by cukal** [comment]
We're moving NFS to ISCSI based datastores and the VM's are included in those the metrics. grtz.

**Comment by jdelvecchio** [comment]
Hi, I'm having the same issue, vmware_vm_disk_*_average has no time series since all of our vms use nfs volumes
Julien

**Comment by jdelvecchio** [comment]
> https://www.vmware.com/support/developer/converter-sdk/conv61_apireference/virtual_disk_counters.html For reference here. I need to look closer at this.

Any update on this ? thanks a lot
