### ISSUE TITLE
Update PyPI package to latest version

### ISSUE THREAD

**Issue by karlism** [pryorda/vmware_exporter#117]
Can you please update PyPI package to latest version? Currently latest available package version is [0.7.4](https://pypi.org/project/vmware-exporter/#history).

**Comment by pryorda** [comment]
The issue was that semantic_release was failing to push up to pypi because they want us to use real content types. YAY!. The fix is here: https://github.com/pryorda/vmware_exporter/blob/master/setup.py#L10 and new versions are being pushed out now. 

Thanks

**Comment by karlism** [comment]
@pryorda, thank you! Successfully updated `vmware-exporter` to latest version by using `pip`.
