### ISSUE TITLE
Host metrics disappear when it disconnects from vCenter

### ISSUE THREAD

**Issue by karlism** [pryorda/vmware_exporter#120]
Hello,

We experienced network issues during the night which caused ESXi hosts to disconnect from vCenter.
What surprised us was that we didn't receive alerts which are based on `vmware_host_connection_state` metric. During our investigation we noticed that metrics for specific `host_name` disappeared from metrics reported by `vmware_exporter` at the same time when hosts disconnected from vCenter. During this time hosts were never removed from vCenter and were still present in it with host state reported as "Not reponding". Can you please look into this issue?

We are running `vmware_exporter` version 0.9.5.

Thanks!

**Comment by dannyk81** [comment]
@karlism good catch, I can reproduce the same in our environment.

This worked in the past, so must have been got broken at some point, I'll try to take a look.

**Comment by dannyk81** [comment]
I believe I found the culprit, according to this:
https://github.com/pryorda/vmware_exporter/blob/7f92526fe6e4be34170f46aedb59a776278942e9/vmware_exporter/vmware_exporter.py#L716-L736

the host metrics collection is skipped if the host is not `poweredOn`...

@pryorda I think at least the `connection_state` should be retrieved regardless of host's power state, wdyt?

**Comment by dannyk81** [comment]
@karlism you can try #124 and see if this solves your problem.

**Comment by karlism** [comment]
@dannyk81, it seems to be working properly, I can see metrics with value `1` and label `state=“disconnected”` when I manually disconnect VMware hosts.
Thanks a lot for your help!
