### ISSUE TITLE
[Feature Request] Add consumed memory metrics

### ISSUE THREAD

**Issue by yu-seki** [pryorda/vmware_exporter#141]
I'd like to get consumed memory metrics.
I noticed that I can get active memory but I can't get consumed memory.
Therefore, I request an additional function for obtaining consumed memory.

**Comment by yu-seki** [comment]
There are two queries to get memory information of virtual machine.

- vmware_vm_mem_usage_average
- vmware_vm_memory_max

vmware_vm_mem_usage_average can get the private percentage of active memory.
There is no query to get consumed memory.
The consumed memory is very important for calculating the percentage of total host consumed memory.

Please refer to the following URL for active memory and consumed memory.
https://www.virtualmvp.com/vmware-consumed-host-memory-vs-active-guest-memory/

**Comment by pryorda** [comment]
I wont be able to get to this for a bit, but if you want to submit a PR with test coverage + updates I can get it pushed out.

**Comment by pryorda** [comment]
Looks like this might already be covered in #132. That PR is just waiting on the unit test updates.
