### ISSUE TITLE
Cluster Tags for better identification

### ISSUE THREAD

**Issue by alecorps** [pryorda/vmware_exporter#151]
Hi guys 

Target : Have grafana dashboard per cluster type, availability zone and region or other tags. I would like a label for these informations.

Why : in some organizations we can have multiple vCenters in different region or country. In each vCenter we can have different use cases or clusters type : Oracle Cluster, Customer Clusters, Test Clusters, Windows Clusters, etc. Separate clusters based on different label for capacity planning, troubleshooting, reporting purposes in dashboards should be a very usefull   feature.

How :

To do that i thought 3 options :

- we can get all tags per object at the begining of the process and we can define labels for each metrics like perf metrics for vms which is more dynamic. As this modification is quite big, do you think it's a good idea  ?

- rather that add dynamically tags in label, we  could define some extra_labels in the config.yml and each label has to be a tag in vcenter. The value of tag will be the label value or None if the tag is not found on the object. It is more static than the first solution and require a mapping between tag defined in vcenter and extra_labels defined in config.yml but easier to implement with no mass change in actual code. 

- last option and i think better one, As the tag is on cluster level, we can also implement a new collector for cluster to collect tags and maybe few metrics if needed (evc / ha) for example.
With that it will be easily to map cluster with tags (az,region, etc) and host/vm with cluster as the label cluster is already collected.
With that it will be easy to have cluster Dashboard with all information of cluster and hosts/vms

What do you think ?

Thanks for your answers

**Comment by pryorda** [comment]
How are you running the exporter and scraping from it?

**Comment by alecorps** [comment]
Running the exporter in a container and displays metrics in grafana.

**Comment by pryorda** [comment]
Typically you can use telegraf to inject tags. You can also do relabels in prometheus to change information that was imported. For instance, snmp_exporter has an example where it changes the labels for targets.

**Comment by alecorps** [comment]
do you recommend using telegraf for tags rather than doing it in the exporter ?

**Comment by pryorda** [comment]
For now yes. I'm not sure If I will be able to get to adding tags in the near future.

**Comment by alecorps** [comment]
I will try to do it soon and let you know
