### ISSUE TITLE
vmware_exporter bin file version

### ISSUE THREAD

**Issue by Alexvianet** [pryorda/vmware_exporter#154]
How can I get the package version?
Can we promote something like:
`/usr/local/bin/vmware_exporter -v , --version`
to get package version like in node_exporter

**Comment by finkr** [comment]
PR https://github.com/pryorda/vmware_exporter/pull/280

**Comment by finkr** [comment]
This feature was added in release  [v0.17.1](https://github.com/pryorda/vmware_exporter/releases/tag/v0.17.1).

**Comment by pryorda** [comment]
Closed
