### ISSUE TITLE
Get events on prometheus

### ISSUE THREAD

**Issue by alecorps** [pryorda/vmware_exporter#161]
Hello guys,

I would like add ha events collect in exporter.
I already did it in my lab to collect ha events (warning and error) to catch some event, do some grafana dashboards.
Like the vm or host metrics it can be disabled in config file.

What do you think to add HA EVENTS collect in the exporter ?

Thanks

Alban

**Comment by pryorda** [comment]
I'm always open to this. Want to do one more PR?

**Comment by alecorps** [comment]
I will asap
Thanks

**Comment by alecorps** [comment]
https://github.com/pryorda/vmware_exporter/pull/165

**Comment by alecorps** [comment]
After some reflection, it's not a good use case. We will send the log to ELK and will use datasource ELK on grafana
