### ISSUE TITLE
KeyError: 'specs_size'

### ISSUE THREAD

**Issue by finkr** [pryorda/vmware_exporter#163]
I upgraded from 0.9.7 to 0.11.0, I got error:

    KeyError: 'specs_size'

It's related to this new feature _Split specs in multiple chunks of 5000 specs_ (PR #158).

To workaround, I had to add `specs_size: 5000` to the yaml file, like 
    
    default:
        vsphere_host: "vcenter"
        vsphere_user: "user"
        vsphere_password: "password"
        ignore_ssl: False
        specs_size: 5000

It would be nice to set a default value, and explain how and why it should be tuned (with a link to VMware?)

**Comment by pryorda** [comment]
@finkr thank you for testing. @alecorps can you take a look? Otherwise I'll get to it this evening.

**Comment by alecorps** [comment]
Hello, i will check that asap
Thanks

**Comment by pryorda** [comment]
Pretty sure this was fixed. let me know if it wasn't.
