### ISSUE TITLE
How to integrate vmware_exporter with prometheus

### ISSUE THREAD

**Issue by ranjithfd** [pryorda/vmware_exporter#172]
Hi Team,

 Can you please share the steps to integrate vmware_exporter with prometheus

**Comment by kremers** [comment]
Hi @ranjithfd jsut like any other exporter:
1. You run the exporter somewhere, (i.e. in Kubernetes or Docker, see Readme.md)
2. You check that it is available at its port  http://WHEREEVERYOURUNIT:9272/metrics
3. You write prometheus config to scrape it https://prometheus.io/docs/prometheus/latest/configuration/configuration/

**Comment by pryorda** [comment]
The readme has this covered as well. 

Closing this out for now. Let us know if you still have questions.
