### ISSUE TITLE
vmware_vm_snapshot_timestamp_seconds not showing result in seconds

### ISSUE THREAD

**Issue by andbuitra** [pryorda/vmware_exporter#176]
Currently the "vmware_vm_snapshot_timestamp_seconds" metric does not output the result in seconds. I currently have three snapshots no older than three days but if the converted value from seconds where to be made it would show that the youngest snapshot is 50 years old. According to RV Tools connecting directly to the vcenter server these are no older than yesterday.

I did upgrade today to the latest release available for vmware_exporter and the snapshots were already there. However I don't think the update would be related since the exporter is supposed to be scrapping directly from the API.

**Comment by andbuitra** [comment]
By typing the "50 years old" I came to the realization that this might be in fact just the time in Unix time. When doing the arithmetic it does checkout. This is, however, misleading since there's no mention of it in the HELP from the metric itself.

**Comment by pryorda** [comment]
Hey @andbuitra, Sorry about the delay on this. createTime is a state to show the creation epoch timestamp of when the snapshot was taken. you should be able to use a now - vmware_vm_snapshot_timestamp_seconds to get the correct age. 

https://www.vmware.com/support/developer/converter-sdk/conv61_apireference/vim.vm.SnapshotTree.html#createTime
