### ISSUE TITLE
Issue running the exporter in a docker-compose file

### ISSUE THREAD

**Issue by seyfbarhoumi** [pryorda/vmware_exporter#178]
Hello guys,
i've been using this exporter to collect prometheus metrics from a vcenter using a docker container, everything was working fine. Once i tried to use it as a service within a docker-compose file with the same configuration im facing issues. Does anybody face the same problem?

**Comment by dannyk81** [comment]
You're not giving us much to work with... what exactly happens? what is failing? any relevant logs?

**Comment by pryorda** [comment]
@seyfbarhoumi Just following up on this. Have you updated all the variables with real information? Can you provide us logs of the issue?

**Comment by seyfbarhoumi** [comment]
Sorry for the late answer guys. In fact, i did some modifications to the code to make it collect only metrics from a desired source, this helped me to gain a lot of performance. so i pass what i want to fetch on an env variable called VSHPERE_COLLECT_ONLY, in this example im collecting metrics of datasources, and as you can see here it works perfectly when im running a container:

hon/vmware_exporter >docker run -it --rm  -p 9272:9272 -e VSPHERE_COLLECT_ONLY=DS -e VSPHERE_USER=********** -e VSPHERE_PASSWORD=********** -e VSPHERE_HOST=bams-vcenter -e VSPHERE_IGNORE_SSL=True -e VSPHERE_SPECS_SIZE=2000 --name exporter seif

2020-03-11 08:23:21,439 INFO:Starting web server on port 9272
2020-03-11 08:23:25,813 INFO:Start collecting metrics from bams-vcenter
2020-03-11 08:23:25,813 INFO:Fetching vim.Datastore inventory
2020-03-11 08:23:25,815 INFO:Retrieving service instance content
2020-03-11 08:23:26,383 INFO:Retrieved service instance content
2020-03-11 08:23:28,313 INFO:Fetched vim.Datastore inventory (0:00:02.499732)
2020-03-11 08:23:32,578 INFO:Finished collecting metrics from bams-vcenter
2020-03-11 08:23:35,810 INFO:Start collecting metrics from bams-vcenter
2020-03-11 08:23:35,810 INFO:Fetching vim.Datastore inventory
2020-03-11 08:23:35,810 INFO:Retrieving service instance content
2020-03-11 08:23:36,233 INFO:Retrieved service instance content
2020-03-11 08:23:38,382 INFO:Fetched vim.Datastore inventory (0:00:02.571751)
2020-03-11 08:23:42,559 INFO:Finished collecting metrics from bams-vcenter

Concerning docker-compose method, this is how my docker-compose file looks like:

version: '3'
services:
  exporter:
    image: seif
    ports:
        - "9272:9272"
    environment:
        VSPHERE_HOST: "bams-vcenter"
        VSPHERE_USER: "**********"
        VSPHERE_PASSWORD: "**********"
        VSPHERE_IGNORE_SSL: "True"
        VSPHERE_COLLECT_ONLY: "DS"
    command: ["-l","DEBUG"]

And these are the logs:

Starting vmware_exporter_exporter_1 ... done
Attaching to vmware_exporter_exporter_1
exporter_1  | 2020-03-11 08:31:15,545 INFO:Starting web server on port 9272
exporter_1  | 2020-03-11 08:31:15,813 INFO:Start collecting metrics from bams-vcenter
exporter_1  | 2020-03-11 08:31:15,813 INFO:Fetching vim.Datastore inventory
exporter_1  | 2020-03-11 08:31:15,815 INFO:Retrieving service instance content
exporter_1  | 2020-03-11 08:31:20,827 ERROR:Traceback (most recent call last):
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 897, in _async_render_GET
exporter_1  |     yield self.generate_latest_metrics(request)
exporter_1  | twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'socket.gaierror'>: [Errno -3] Try again
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:501:errback
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
exporter_1  | --- <exception caught here> ---
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:248:datastore_inventory
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:220:batch_fetch_properties
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:210:content
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:198:connection
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
exporter_1  | /usr/local/lib/python3.6/site-packages/pyVim/connect.py:847:SmartConnect
exporter_1  | /usr/local/lib/python3.6/site-packages/pyVim/connect.py:726:__FindSupportedVersion
exporter_1  | /usr/local/lib/python3.6/site-packages/pyVim/connect.py:643:__GetServiceVersionDescription
exporter_1  | /usr/local/lib/python3.6/site-packages/pyVim/connect.py:608:__GetElementTree
exporter_1  | /usr/local/lib/python3.6/http/client.py:1262:request
exporter_1  | /usr/local/lib/python3.6/http/client.py:1308:_send_request
exporter_1  | /usr/local/lib/python3.6/http/client.py:1257:endheaders
exporter_1  | /usr/local/lib/python3.6/http/client.py:1036:_send_output
exporter_1  | /usr/local/lib/python3.6/http/client.py:974:send
exporter_1  | /usr/local/lib/python3.6/http/client.py:1415:connect
exporter_1  | /usr/local/lib/python3.6/http/client.py:946:connect
exporter_1  | /usr/local/lib/python3.6/socket.py:704:create_connection
exporter_1  | /usr/local/lib/python3.6/socket.py:745:getaddrinfo
exporter_1  | ]]
exporter_1  | --- <exception caught here> ---
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:467:_vmware_get_datastores
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/defer.py:99:parallelize
exporter_1  | ]]
exporter_1  | 
exporter_1  | Unhandled error in Deferred:
exporter_1  | 
exporter_1  | Traceback (most recent call last):
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
exporter_1  |     self._startRunCallbacks(fail)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
exporter_1  |     self._runCallbacks()
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
exporter_1  |     current.result = callback(current.result, *args, **kw)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
exporter_1  |     _inlineCallbacks(r, g, status)
exporter_1  | --- <exception caught here> ---
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
exporter_1  |     result = result.throwExceptionIntoGenerator(g)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
exporter_1  |     return g.throw(self.type, self.value, self.tb)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 248, in datastore_inventory
exporter_1  |     properties
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
exporter_1  |     result = result.throwExceptionIntoGenerator(g)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
exporter_1  |     return g.throw(self.type, self.value, self.tb)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 220, in batch_fetch_properties
exporter_1  |     content = yield self.content
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
exporter_1  |     result = result.throwExceptionIntoGenerator(g)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
exporter_1  |     return g.throw(self.type, self.value, self.tb)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 210, in content
exporter_1  |     connection = yield self.connection
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
exporter_1  |     result = result.throwExceptionIntoGenerator(g)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
exporter_1  |     return g.throw(self.type, self.value, self.tb)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 198, in connection
exporter_1  |     sslContext=context,
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
exporter_1  |     result = inContext.theWork()
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
exporter_1  |     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
exporter_1  |     return self.currentContext().callWithContext(ctx, func, *args, **kw)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
exporter_1  |     return func(*args,**kw)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 847, in SmartConnect
exporter_1  |     sslContext)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 726, in __FindSupportedVersion
exporter_1  |     httpProxyPort)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 643, in __GetServiceVersionDescription
exporter_1  |     httpProxyHost, httpProxyPort)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 608, in __GetElementTree
exporter_1  |     conn.request("GET", path)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1262, in request
exporter_1  |     self._send_request(method, url, body, headers, encode_chunked)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1308, in _send_request
exporter_1  |     self.endheaders(body, encode_chunked=encode_chunked)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1257, in endheaders
exporter_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1036, in _send_output
exporter_1  |     self.send(msg)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 974, in send
exporter_1  |     self.connect()
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1415, in connect
exporter_1  |     super().connect()
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 946, in connect
exporter_1  |     (self.host,self.port), self.timeout, self.source_address)
exporter_1  |   File "/usr/local/lib/python3.6/socket.py", line 704, in create_connection
exporter_1  |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
exporter_1  |   File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
exporter_1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
exporter_1  | socket.gaierror: [Errno -3] Try again
exporter_1  | 
exporter_1  | Unhandled error in Deferred:
exporter_1  | 
exporter_1  | Traceback (most recent call last):
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
exporter_1  |     self._startRunCallbacks(fail)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
exporter_1  |     self._runCallbacks()
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
exporter_1  |     current.result = callback(current.result, *args, **kw)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
exporter_1  |     _inlineCallbacks(r, g, status)
exporter_1  | --- <exception caught here> ---
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
exporter_1  |     result = result.throwExceptionIntoGenerator(g)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
exporter_1  |     return g.throw(self.type, self.value, self.tb)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 360, in datastore_labels
exporter_1  |     dcs = yield self.datacenter_inventory
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
exporter_1  |     result = result.throwExceptionIntoGenerator(g)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
exporter_1  |     return g.throw(self.type, self.value, self.tb)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 328, in datacenter_inventory
exporter_1  |     content = yield self.content
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
exporter_1  |     result = result.throwExceptionIntoGenerator(g)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
exporter_1  |     return g.throw(self.type, self.value, self.tb)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 210, in content
exporter_1  |     connection = yield self.connection
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
exporter_1  |     result = result.throwExceptionIntoGenerator(g)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
exporter_1  |     return g.throw(self.type, self.value, self.tb)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 198, in connection
exporter_1  |     sslContext=context,
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
exporter_1  |     result = inContext.theWork()
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
exporter_1  |     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
exporter_1  |     return self.currentContext().callWithContext(ctx, func, *args, **kw)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
exporter_1  |     return func(*args,**kw)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 847, in SmartConnect
exporter_1  |     sslContext)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 726, in __FindSupportedVersion
exporter_1  |     httpProxyPort)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 643, in __GetServiceVersionDescription
exporter_1  |     httpProxyHost, httpProxyPort)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 608, in __GetElementTree
exporter_1  |     conn.request("GET", path)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1262, in request
exporter_1  |     self._send_request(method, url, body, headers, encode_chunked)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1308, in _send_request
exporter_1  |     self.endheaders(body, encode_chunked=encode_chunked)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1257, in endheaders
exporter_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1036, in _send_output
exporter_1  |     self.send(msg)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 974, in send
exporter_1  |     self.connect()
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1415, in connect
exporter_1  |     super().connect()
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 946, in connect
exporter_1  |     (self.host,self.port), self.timeout, self.source_address)
exporter_1  |   File "/usr/local/lib/python3.6/socket.py", line 704, in create_connection
exporter_1  |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
exporter_1  |   File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
exporter_1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
exporter_1  | socket.gaierror: [Errno -3] Try again

Please note, that even before doing code modifications i had the same issue running this image within a docker compose file or a kubernetes pod with the same error.

**Comment by pryorda** [comment]
Looks like its a get address info error. Are you sure the address is resolvable from the container?

**Comment by pryorda** [comment]
Going to close out for now. Let us know if you still need assistance with this issue.

**Comment by seyfbarhoumi** [comment]
Resolved, had to use FQDN instead of hostname for the VSPHERE_HOST environment variable, thanks for the help.
