### ISSUE TITLE
Need advise to properly set value for specs_size

### ISSUE THREAD

**Issue by mfominov** [pryorda/vmware_exporter#181]
How to properly set  specs_size for scraping all data from vmware?

**Comment by dannyk81** [comment]
I'd say it really depends on the size of your vsphere deployment, specifically the number of VMs in the scraped vCenter, the default (5000) should cover well most deployment sizes, thisnwas tested the PR author on a vCenter with 17K VMs and worked well.

Is there a specific concern? or issue? on your end.

**Comment by mfominov** [comment]
We have a lot of errors when trying to scrape data from vmware.
We scraping all data to create full monitoring solution for our core team.
With increasing of specs_size we see less errors like 
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 997, in _async_render_GET
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 1046, in generate_latest_metrics
    request.finish()
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 286, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1079, in finish
    "Request.finish called on a request after its connection was lost; "
RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```
Current configuration 
3 vcenters 
60 host
2000 vms


PS we = devops team)

**Comment by pryorda** [comment]
@mfominov Were you able to make any progress on fixing this? It seems like you might need to turn up the scrape duration a bit. Does it work when you hit the exporter threshold yourself?

**Comment by mfominov** [comment]
We split to 3 different containers and now we see less connection errors messages in logs

**Comment by alecorps** [comment]
Hello,

On our side it failed only on one vCenter with more than 17K VMs, that's why we added specs size. We have another vCenters with more than 7k VMs and it works well. In all our utilisation we are using the default specs size.
The error message you have, we got it few times and often it was due to the the scrape timeout configured on prometheus but not from the exporter. How many prometheus pull the /metrics in parallel ? In our case it was 3 and our vCenter suffered. We created a cache on the vmware exporter to do only one collect per section at the time. We need to create a PR for that.

You can try to pull the /metrics from a browser on your exporter and check how many times it takes. Based on that you can configure accordingly the scrape timeout and interval on prometheus.

**Comment by mfominov** [comment]
We have only one promethues that scrapes metric.
I think the problem is in vcenter, in some cases it's quite slow and we don't any metrics.
We will try to scrape some data from jxm)
THX every one.

**Comment by pryorda** [comment]
Did you change the scrape duration/timeout inside of prometheus?

**Comment by mfominov** [comment]
Right now no.
Current configuration
```
global:
  scrape_interval: 1m
  scrape_timeout: 20s
  evaluation_interval: 30s
```

**Comment by pryorda** [comment]
scrape timeout is way way way to low for that size. We have ours at 120s with <800 vms, 30ish hosts.

**Comment by mfominov** [comment]
Current config for vmware hosts:
```yaml
scrape_interval: 2m
scrape_timeout: 1m
```

also i moved exporters to k8s.

Thx for help, please close this issue.

**Comment by mfominov** [comment]
Also we increased vmware api rate limit
https://kb.vmware.com/s/article/2107096

**Comment by pryorda** [comment]
Thanks for adding the article and glad you got it resolved.
