### ISSUE TITLE
Config.yml requires default 'default' section

### ISSUE THREAD

**Issue by joereyna** [pryorda/vmware_exporter#182]
https://github.com/pryorda/vmware_exporter/blob/c096e53a37a84fa6c9a55734cbe5ecc0454f01b1/kubernetes/config.yml#L7

I tried running this as is, but got this error:
`/opt/vmware_exporter # python3 vmware_exporter/vmware_exporter.py -c ./kubernetes/config.yml
/usr/local/lib/python3.6/site-packages/yamlconfig.py:63: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(self.infile)
2020-03-12 20:59:45,383 ERROR:Error, you must have a default section in config file (for now)`

After changing 'data' to 'default', this starts to work again.

**Comment by pryorda** [comment]
You can set default section to anything then use the arg to point at your specific section. The read me goes over this. Reopen if you can't get it to function correctly.
