### ISSUE TITLE
Bind to address/interface

### ISSUE THREAD

**Issue by madecto** [pryorda/vmware_exporter#183]
Hello,
I'm happily using your exporter on a VM and I would like to know if there's a chance to bind to specific address(es) or interfaces.

I'm aware of the possibility to use docker to segregate the binary, but I reckon having it listen only on `localhost`, a specific address or even a named interface such as `ens192` - i.e. the management interface of the monitoring VM - would lower maintenance, memory footprint and simplify the architecture.

**Comment by pryorda** [comment]
We welcome pull requests. I don't think setting a bind address would change the memory or maintenance foot print.
