### ISSUE TITLE
vsphere_host query string incompatible with prometheus

### ISSUE THREAD

**Issue by intrand** [pryorda/vmware_exporter#19]
The commit linked below, which changed the query string for the vcenter host from target= to vsphere_host=, broke compatibility with Prometheus.

https://github.com/pryorda/vmware_exporter/commit/7d79dde68a80adec03ecf8dd1e5edfa3e60701e4#diff-53c0cb48872ead8bf7a02d1c967386c0L75

Prometheus will pass, for example, http://123.123.123.123:9272/metrics?target=myvc.example.com

Using the most recent docker container as of writing, you'll get "No vsphere_host defined!" back.

Otherwise, this works well :) Until that's fixed, we're going to use different sections for different vcenters.

Thanks for your hard work!

**Comment by pryorda** [comment]
@intrand Should be fixed. Lemmeno and Ill close this out

**Comment by pryorda** [comment]
Closing this out. Reopen if its not fixed. 

Thanks

**Comment by intrand** [comment]
Working great! Thanks! I really appreciate your fast response on this :)
