### ISSUE TITLE
Issue running Ubuntu 18.04

### ISSUE THREAD

**Issue by tiagoIW** [pryorda/vmware_exporter#209]
Hello, how are you.

I have an trouble trying to run in a single server only, I have other server running ok.

When I try to collect the metrics with the comand:

curl http://127.0.0.1:9272/metrics?vsphere_host=192.168.2.250

I receive below on the exporter:

FirstError[#0, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#1, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: 'NoneType' object has no attribute 'field'

My config.yml

default:
  collect_only:
    datastores: True
    hosts: True
    snapshots: True
    vmguests: True
    vms: True
  ignore_ssl: True
  specs_size: 5000
  fetch_custom_attributes: False
  fetch_tags: False
  vsphere_host: 192.168.2.250
  vsphere_password: 'password'
  vsphere_user: 'root'

I tryed to run as root and as normal user.

**Comment by tiagoIW** [comment]
Someone could help me ?

**Comment by pryorda** [comment]
We prefer to run inside the docker container. For setup instructions refer to the DockerFile. This looks like an issue with pulling the data from vcenter. Validate credentials have access to everything in vsphere.

**Comment by tiagoIW** [comment]
Thank You... its running under docker... but, is there anyway to get metrics about twice or more vpshere hosts under one docker ?

**Comment by tiagoIW** [comment]
@pryorda is there anyway to get metrics about twice or more hosts under one docker ?

**Comment by pryorda** [comment]
Not sure I understand that question.

**Comment by tiagoIW** [comment]
I need to get metrics about 3 vmware hosts on the same docker, is it possible ?

**Comment by pryorda** [comment]
Yes, you just need to set up different sections. The readme describes this.

**Comment by tiagoIW** [comment]
Thank you so much!!!
