### ISSUE TITLE
UnicodeEncodeError when collecting data

### ISSUE THREAD

**Issue by is4it-lab** [pryorda/vmware_exporter#21]
I've got this error messege when collecting data from one vcenter. An other vcenter works fine with the same config. 
The Unicode code for u'\xe4' means an "ä" - but there no such character in any name ...

web.Server Traceback (most recent call last):
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 44: ordinal not in range(128)
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:577 in _runCallbacks
```
576                    try:
577                        current.result = callback(current.result, *args, **kw)
578                        if current.result is current:
```
/opt/prometheus/vmware_exporter/vmware_exporter.py:129 in generate_latest_metrics
```
128                            k, v.replace('\\', r'\\').replace('\n', r'\n').replace('"', r'\"')).decode('ascii')
129                         for k, v in sorted(labels.items())]))
130                else:
```
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 44: ordinal not in range(128)

**Comment by pryorda** [comment]
I would say that there is a special character somewhere. Ill see if i can whip up some debug statements around that.

**Comment by pryorda** [comment]
@is4it-lab can you add the log around current.result and see if that reveals anything to you?
https://github.com/pryorda/vmware_exporter/blob/master/vmware_exporter/vmware_exporter.py#L124
make it look like: 
```
for name, labels, value in metric.samples:
    log("Name: {}".format(name))
    log("Labels: {}".format(labels))
    log("Value: {}".format(value))
    if labels:
```

If you're unable to do this, I can create a branch and separate docker image for you to test with

**Comment by is4it-lab** [comment]
Hi,
the debug finds out the problem.
There were some snapshot names containing german Umlaute

after renaming the snapshots it works fine.

Thank you.

**Comment by lkx007** [comment]
@pryorda why vmware_exporter use "ascii" rather than "utf-8"?
