### ISSUE TITLE
Prometheus error 'expected equal, got "LNAME"'

### ISSUE THREAD

**Issue by syphix** [pryorda/vmware_exporter#214]
Hello,

i ran the exporter with a small cluster and it worked just fine. Now that i changed it to a larger one prometheus cant scrape the data anymore.

Error in frontend:
expected equal, got "LNAME"

In Prometheus log:

`level=warn ts=2020-07-13T10:08:53.895Z caller=scrape.go:930 component="scrape manager" scrape_pool=vmware-exporter target=http://localhost:9272/metrics msg="append failed" err="expected equal, got \"LNAME\""`

Im using the default config provided in the readme.
Thanks in advance.

**Comment by pryorda** [comment]
@syphix What was the issue here or did you close it because I was slow to respond?
