### ISSUE TITLE
Is it possible to collect metrics from a specific datacenter ?

### ISSUE THREAD

**Issue by seyfbarhoumi** [pryorda/vmware_exporter#215]
I wanted to gather metrics from only one datacenter in our hierarchy , this will boost performance as it will collect less metrics and that's what i need actually, is that possible or is there any future release including this possibility ?

**Comment by pryorda** [comment]
This would be a feature request. However, you can do this filtering on the Prometheus side if you wanted.

**Comment by pryorda** [comment]
https://docs.newrelic.com/docs/integrations/prometheus-integrations/install-configure/ignore-or-include-prometheus-metrics

**Comment by seyfbarhoumi** [comment]
It would be great as a future feature as it will reduce scraping time. Doing it in the Prometheus side is not what I needed but thanks for the information, good luck .
