### ISSUE TITLE
expected equal, got "LNAME"

### ISSUE THREAD

**Issue by Kraktorist** [pryorda/vmware_exporter#216]
Hello,

I've just installed the latest vmware_exporter instance and found it very helpful. Thank you for good tool!
But I faced with the following error during metrics scraping:

`expected equal, got "LNAME"`

I tried to google the error and found this happens because of wrong metrics format. After some tests I found that vmware_exporter uses Vmware custom attributes as labels. In our infrastructure we use custom attributes "Build Date" and "Build Ticket" for virtual machines. These  attributes contain ' ' (space) in the key names and the exporter shows them without escaping

`vmware_vm_template{Build Date="5/25/2012",Build Ticket="xxxxxxxxx",cluster_name="PROD",dc_name="DC",host_name="servername.domain.com",tags="n/a",vm_name="myvmname"} 0.0` 

`vmware_vm_guest_disk_capacity{Build Date="n/a",Build Ticket="n/a",cluster_name="Prod",dc_name="DC",host_name="servername.domain.com",partition="C:\\",tags="n/a",vm_name="myvmname"} 64422408192.0
`
At the same time I don't have any attributes for hosts and datastores and my prometheus server scrapes them without problem.
Am I right that it's the root cause of my problem?
Thanks.

PS:  it's working without errors when I set fetch_custom_attributes to False.

**Comment by pryorda** [comment]
@Kraktorist Thank you for the analysis on this. The attribute keys should like be converted to lower and snake case.

**Comment by pryorda** [comment]
This should be fixed in 0.13.1.
