### ISSUE TITLE
Everytime I rebooted one of the ESX Hosts, the Exporter stopped collecting the metrics

### ISSUE THREAD

**Issue by linhuisheng** [pryorda/vmware_exporter#219]
Everytime I rebooted one of the ESX Hosts, the Exporter stopped collecting the metrics

**Comment by pryorda** [comment]
What version are you running and what is the error?

**Comment by linhuisheng** [comment]
When I restart a physical machine, the collection fails this time, and then the performance of all exhost hosts on this VCenter is all broken, and the original physical machine generates alarm and is restored.How to deal with this situation?

![image](https://user-images.githubusercontent.com/8087304/90478191-5b696d00-e15f-11ea-9872-08489aa9d7fc.png)
![image](https://user-images.githubusercontent.com/8087304/90478185-573d4f80-e15f-11ea-9d67-355318585ed6.png)

**Comment by pryorda** [comment]
Closed for inactivity.
