### ISSUE TITLE
Device backing ID

### ISSUE THREAD

**Issue by cihantunali** [pryorda/vmware_exporter#234]
Hello,

Is there any way to collect naa.id from datastore? Need to match with storage itself to create dashboards storage vs vmware. Thank you.

![image](https://user-images.githubusercontent.com/52137019/100884494-97cc9900-34c2-11eb-9e41-ed8ef276411a.png)

**Comment by pryorda** [comment]
This will not be done. We welcome PRs if you want to contribute.
