### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by pushan9** [pryorda/vmware_exporter#236]
I am getting context deadline exceeded on Prometheus, however I am able to get metrics when I do curl.
Can anyone get this addressed

**Comment by pryorda** [comment]
What is the timeout set to on the prometheus end?

**Comment by pushan9** [comment]
> What is the timeout set to on the prometheus end?
Here is my Prometheus config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['myIP:9100']


  - job_name: vmware_export
    metrics_path: /metrics
    static_configs:
    - targets:
      - Vcenter-1
      - Vcenter-2
	  
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: MyIP:9272

**Comment by pushan9** [comment]
> What is the timeout set to on the prometheus end?
Below is my Prometheus configuration
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['myIP:9100']


  - job_name: vmware_export
    metrics_path: /metrics
    static_configs:
    - targets:
      - Vcenter-1
      - Vcenter-2
	  
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: MyIP:9272

**Comment by pushan9** [comment]
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['myIP:9100']


  - job_name: vmware_export
    metrics_path: /metrics
    static_configs:
    - targets:
      - Vcenter-1
      - Vcenter-2
	  
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: MyIP:9272

**Comment by pushan9** [comment]
(global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['myIP:9100']


  - job_name: vmware_export
    metrics_path: /metrics
    static_configs:
    - targets:
      - Vcenter-1
      - Vcenter-2
	  
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: MyIP:9272
	  
	  )

**Comment by pushan9** [comment]
(global:
  scrape_interval:     15s #### Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s #### Evaluate rules every 15 seconds. The default is every 1 minute.
  #### scrape_timeout is set to the global default (10s).

#### Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      #### - alertmanager:9093

#### Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  #### - "first_rules.yml"
  #### - "second_rules.yml"

#### A scrape configuration containing exactly one endpoint to scrape:
#### Here it's Prometheus itself.
scrape_configs:
  #### The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    #### metrics_path defaults to '/metrics'
    #### scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['myIP:9100']


  - job_name: vmware_export
    metrics_path: /metrics
    static_configs:
    - targets:
      - Vcenter-1
      - Vcenter-2
	  
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: MyIP:9272
	  
	  )

**Comment by pushan9** [comment]
fixed it, thanks
