### ISSUE TITLE
Limiting the collected Metrics

### ISSUE THREAD

**Issue by Yagyansh** [pryorda/vmware_exporter#240]
Hi. I have just started using vmware_exporter version 1.13.2. Since I am new to this exporter, I have a couple of questions in mind.

Is the exporter production ready? I mean any known issues that I need to keep in mind, that can affect the performance of my VCenter? 

Can I limit the metrics manually I am scraping? I know there is a collect only parameter, but I want to know if further metric collection can be reduced? For eg. In the VM metrics, I don't need latencies and stuff, I need only a couple of metrics for the VMs, can I specify somewhere to not scrape the remaining metrics?

**Comment by pryorda** [comment]
You could remove it from the metrics inside the code. However, it would probably be better to limit it on the prometheus side.
