### ISSUE TITLE
Hardware sensors Information.

### ISSUE THREAD

**Issue by Yagyansh** [pryorda/vmware_exporter#241]
Hi. It would be great to get the status of the hardware sensors of an ESX host. I mean if not the exact output, only to check if any of the hardware sensors have any issues. Something like Nagios based agent Check_MK does.
https://checkmk.com/integrations/esx_vsphere_sensors

Temperature, Power supplies, Fan, Memory DIMM etc.

Some of the metrics as per VMWare Docs.
![image](https://user-images.githubusercontent.com/15364964/105614532-09083880-5df0-11eb-978c-a067c980aa40.png)
https://docs.vmware.com/en/vRealize-Operations-Manager/8.1/com.vmware.vcom.metrics.doc/GUID-C3CAAE15-2E83-431F-8F2D-C5297A3B6EA9.html

Is this a possibility?

**Comment by pryorda** [comment]
It looks like this is being handled via #255
