### ISSUE TITLE
Error when input old verison vsphere

### ISSUE THREAD

**Issue by ivantang117** [pryorda/vmware_exporter#245]
I am running the latest version on Centos using docker. It works find that I input vsphere v5+ host as environment variables. 

However, I had 4 standalone old version(v4.1) vsphere. When I request data I see the following error:

`2021-03-02 15:10:37,049 INFO:Starting web server on port 9272
2021-03-02 15:10:49,992 INFO:Start collecting metrics from XXXXXXX
2021-03-02 15:10:49,992 INFO:Starting vm metrics collection
2021-03-02 15:10:49,992 INFO:Fetching vim.VirtualMachine inventory
2021-03-02 15:10:49,994 INFO:Retrieving service instance content
2021-03-02 15:10:49,997 INFO:START: _vmware_get_vm_perf_manager_metrics
2021-03-02 15:10:49,997 INFO:Fetching vim.Datastore inventory
2021-03-02 15:10:49,997 INFO:Starting host metrics collection
2021-03-02 15:10:49,997 INFO:Fetching vim.HostSystem inventory
2021-03-02 15:10:49,998 INFO:START: _vmware_get_host_perf_manager_metrics
2021-03-02 15:10:50,295 INFO:Retrieved service instance content
2021-03-02 15:10:53,093 ERROR:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1840, in _async_render_GET
    yield self.generate_latest_metrics(request)
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#1, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'pyVmomi.VmomiSupport.vmodl.query.InvalidProperty'>: (vmodl.query.InvalidProperty) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   name = 'guest.toolsVersionStatus2'
}
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:501:errback
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py:746:vm_inventory
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py:575:batch_fetch_properties
/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.7/site-packages/vmware_exporter/helpers.py:62:batch_fetch_properties
/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py:706:<lambda>
/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py:512:_InvokeMethod
/usr/local/lib/python3.7/site-packages/pyVmomi/SoapAdapter.py:1397:InvokeMethod
]]
--- <exception caught here> ---
/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py:1053:vm_labels
/usr/local/lib/python3.7/site-packages/vmware_exporter/defer.py:99:parallelize
]]
--- <exception caught here> ---
/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py:1467:_vmware_get_vms
/usr/local/lib/python3.7/site-packages/vmware_exporter/defer.py:99:parallelize
]]

Unhandled error in Deferred:

Traceback (most recent call last):
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1053, in vm_labels
    virtual_machines, host_labels = yield parallelize(self.vm_inventory, self.host_labels)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/defer.py", line 99, in parallelize
    results = yield defer.DeferredList(args, fireOnOneErrback=True)
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'pyVmomi.VmomiSupport.vmodl.query.InvalidProperty'>: (vmodl.query.InvalidProperty) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   name = 'guest.toolsVersionStatus2'
}
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:501:errback
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py:746:vm_inventory
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py:575:batch_fetch_properties
/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.7/site-packages/vmware_exporter/helpers.py:62:batch_fetch_properties
/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py:706:<lambda>
/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py:512:_InvokeMethod
/usr/local/lib/python3.7/site-packages/pyVmomi/SoapAdapter.py:1397:InvokeMethod
]]

2021-03-02 15:10:53,177 INFO:Fetched vim.HostSystem inventory (0:00:03.179730)
2021-03-02 15:10:54,261 INFO:Finished host metrics collection`

Is it related to the vsphere version?

**Comment by pryorda** [comment]
I'm not sure. I dont have an old version to test with. Closing for now.
