### ISSUE TITLE
Feature request: make the vm perf list configurable

### ISSUE THREAD

**Issue by dannyk81** [pryorda/vmware_exporter#26]
Currently the list of metrics collected per each VM is hard-coded, this presents two issues:
1) additional metrics that may be needed are difficult to add (requires a new version)
2) (as in our case) we would like to skip some metrics that we don't need and make the scrapes shorter

I think a similar approach to `collect_only` would work here as well.

WDYT @pryorda?

**Comment by pryorda** [comment]
I would like to see it queue the actions and just collect it all. Then you can control the discards in prometheus. Or...

You could set a regex for the metrics you want?

**Comment by dannyk81** [comment]
on large clusters with hundreds of VMs, I don't think it's realistic to collect all available metrics within a reasonable time interval.

**Comment by pryorda** [comment]
Should this be closed since you added the toggle for disk flags.

**Comment by pryorda** [comment]
@dannyk81 Is the fork public and do you want to merge some of the logic? If you guys have already done some of the work, I would hate to reinvent the wheel.

**Comment by dannyk81** [comment]
it's not public, but you won't like what we did 😅 

```diff
diff --git a/vmware_exporter/vmware_exporter.py b/vmware_exporter/vmware_exporter.py
index 859c28d..e26fc95 100755
--- a/vmware_exporter/vmware_exporter.py
+++ b/vmware_exporter/vmware_exporter.py
@@ -489,13 +489,13 @@ class VMWareMetricsResource(Resource):
         perf_list = [
             'cpu.ready.summation',
             'cpu.usage.average',
-            'cpu.usagemhz.average',
-            'disk.usage.average',
-            'disk.read.average',
-            'disk.write.average',
+            # 'cpu.usagemhz.average',
+            # 'disk.usage.average',
+            # 'disk.read.average',
+            # 'disk.write.average',
             'mem.usage.average',
-            'net.received.average',
-            'net.transmitted.average',
+            # 'net.received.average',
+            # 'net.transmitted.average',
         ]

         # Prepare gauges
```

Obviously this is not the way to solve this...

**Comment by pryorda** [comment]
Ill start getting a completely list of metrics from https://www.vmware.com/support/developer/converter-sdk/conv61_apireference/vim.PerformanceManager.html then we can decide how we want to handle it.

**Comment by dannyk81** [comment]
Sounds good! 😄

**Comment by pryorda** [comment]
@dannyk81 Since we decreased the amount of calls via PropertyCollectors do you think this is still needed?

**Comment by dannyk81** [comment]
I was meaning to close this indeed, given the current prop collector we have no concern with pulling all the metrics.

Although not directly related to this issue, but for future work I wonder if we can make things more flexible here, specifically for adding additional metrics to collect.
