### ISSUE TITLE
Error when scraping host metrics

### ISSUE THREAD

**Issue by neuromantik33** [pryorda/vmware_exporter#264]
Hello I'm encountering an error when trying to scrape the host metrics of my vcenter. I'm running the latest version under docker and here is my config

```yaml
version: '2.4'
services:
  vmware_exporter:
    environment:
      VSPHERE_USER: <redacted>
      VSPHERE_PASSWORD: <redacted>
      VSPHERE_HOST: <redacted>
      VSPHERE_IGNORE_SSL: "True"
      VSPHERE_COLLECT_HOSTS: "True"
      VSPHERE_COLLECT_DATASTORES: "False"
      VSPHERE_COLLECT_VMS: "False"
      VSPHERE_COLLECT_VMGUESTS: "False"
      VSPHERE_COLLECT_SNAPSHOTS: "False"
      VSPHERE_FETCH_CUSTOM_ATTRIBUTES: "False"
      VSPHERE_FETCH_TAGS: "False"
      VSPHERE_FETCH_ALARMS: "False"
    image: pryorda/vmware_exporter:v0.16.0
    ports:
    - 9272:9272/tcp
```
When I used multiple accounts (one monitoring, one administrator) and the bug remains. Here is the exacted log (redacted of sensitive information).
```
$ docker-compose up -d
Recreating vsphere_vmware_exporter_1 ... done

$ curl localhost:9272/metrics && echo ''
# Collection failed

$ docker logs vsphere_vmware_exporter_1 
2021-04-02 10:24:12,846 INFO:Starting web server on port :9272
2021-04-02 10:24:16,793 INFO:Start collecting metrics from <redacted>
2021-04-02 10:24:16,794 INFO:Starting host metrics collection
2021-04-02 10:24:16,794 INFO:Fetching vim.HostSystem inventory
2021-04-02 10:24:16,794 INFO:Retrieving service instance content
2021-04-02 10:24:16,796 INFO:START: _vmware_get_host_perf_manager_metrics
2021-04-02 10:24:17,744 INFO:Retrieved service instance content
2021-04-02 10:24:18,334 INFO:Fetched vim.HostSystem inventory (0:00:01.540535)
2021-04-02 10:24:22,391 ERROR:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1922, in _async_render_GET
    yield self.generate_latest_metrics(request)
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'ValueError'>: dictionary update sequence element #1 has length 1; 2 is required
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:477:callback
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:580:_startRunCallbacks
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:662:_runCallbacks
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1514:gotResult
--- <exception caught here> ---
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1445:_inlineCallbacks
/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py:1698:_vmware_get_hosts
]]

2021-04-02 10:24:22,393 INFO:FIN: _vmware_get_host_perf_manager_metrics
```
FYI I'm running vCenter 6.7u3. If I deactivate the host metrics and set everything else to true, everything seems to work.

**Comment by pryorda** [comment]
What are the permissions on the account?

**Comment by neuromantik33** [comment]
One of the used permissions was `monitoring`, the other was `administrator`

![image](https://user-images.githubusercontent.com/19826274/113463284-422edb80-9425-11eb-8f33-d0457f9d849c.png)

**Comment by pryorda** [comment]
Odd. Not 100% sure why its happening. Both have access to read the hosts?

**Comment by neuromantik33** [comment]
I'm not sure what you mean, I have administrator access on a dc but not on vcenter itself. The monitoring user account should have access to everything readonly, is there a vcenter api you can point me to in order to figure out if it's an ACL issue?

**Comment by neuromantik33** [comment]
Well I downgraded to v0.14.3 and everything works much better, so it's definetly related to the sensor data (maybe I don't have any in my cluster?).. I'm downgrading for now but hopefully this can help you narrow down the problem ;)

**Comment by pryorda** [comment]
Thanks for that. Ill look more. I can add a nil check around it.

**Comment by neuromantik33** [comment]
I printed out a couple of errors regarding sensors (I put a giant `try..except` inside the inner sensor loop)
```
021-04-09 18:08:46,072 INFO:Error: 'sensorStatus', sensor: numericSensorInfo:name=VMware
2021-04-09 18:08:46,068 INFO:Error: 'name', sensor:  0x80000a60:type=Software Components:sensorStatus=green:value=0:unitModifier=0:unit=
2021-04-09 18:08:46,076 INFO:Error: dictionary update sequence element #1 has length 1; 2 is required, sensor: numericSensorInfo:name=VMware net-vmxnet3 1.1.3.0-3vmw.600.0.0.2494585 2015-02-06 02:37:02.000:type=Software Components:sensorStatus=green:value=0:unitModifier=0:unit=
```

The block of code is really quite dump (I'm not a python dev)
```python
# line 1697
for s in sensors:
    try:...
    except Exception as e:
        logging.info(
            "Error: {error}, sensor: {sensor}".format(
                error=e, sensor=s
            )
        )
```
Is there a way to deactivate the sensor fetching, as it's done with alors with a config option?

Thanks

**Comment by williamb1024** [comment]
I am also having an issue with the sensor parsing.

https://github.com/pryorda/vmware_exporter/blob/c777973112bfaa795ecc6f6a7f1f4f9937843f4f/vmware_exporter/helpers.py#L112-L120

That code combines the sensor information using a ":" (colon) character. 

https://github.com/pryorda/vmware_exporter/blob/c777973112bfaa795ecc6f6a7f1f4f9937843f4f/vmware_exporter/vmware_exporter.py#L1697-L1699

The above code eventually tries to parse the sensor information by splitting on ":" characters. If the contents of a sensor contains a ":" character, everything goes haywire.

**Comment by ywysuibian** [comment]
Agree with https://github.com/pryorda/vmware_exporter/issues/264#issuecomment-843755419
Here is an example of sensor info contains a ":" in its "name", it leads to this issue:
```
            (vim.host.NumericSensorInfo) {
               name = "VMware misc-cnic-register 1.78.75.v60.7-1vmw.600.0.0.2494585 2015-02-06 02:37:02.000",
               healthState = (vim.ElementDescription) {
                  label = "Green",
                  summary = "Sensor is operating under normal conditions",
                  key = "green"
               },
               currentReading = 0,
               unitModifier = 0,
               baseUnits = "",
               rateUnits = <unset>,
               sensorType = "Software Components"
            },
```

**Comment by ywysuibian** [comment]
Agree with https://github.com/pryorda/vmware_exporter/issues/264#issuecomment-843755419
Here is an example of sensor info which contains ":" in its "name" field, it leads to this issue:
```
            (vim.host.NumericSensorInfo) {
               name = "VMware misc-cnic-register 1.78.75.v60.7-1vmw.600.0.0.2494585 2015-02-06 02:37:02.000",
               healthState = (vim.ElementDescription) {
                  label = "Green",
                  summary = "Sensor is operating under normal conditions",
                  key = "green"
               },
               currentReading = 0,
               unitModifier = 0,
               baseUnits = "",
               rateUnits = <unset>,
               sensorType = "Software Components"
            },
```

**Comment by Z903** [comment]
I ran into the same issue and have made a pull request https://github.com/pryorda/vmware_exporter/pull/271

**Comment by Z903** [comment]
I ran into the same issues here pr https://github.com/pryorda/vmware_exporter/pull/271
