### ISSUE TITLE
Security issues : VMware Exporters

### ISSUE THREAD

**Issue by pratik322** [pryorda/vmware_exporter#265]
Hello,

Is there is a way to secure the VMware details instead of using a username and password in the config file? 
How to make sure the connection is secure between the exporter and the Vcenter?

**Comment by pryorda** [comment]
Not sure what you mean. This uses ssl and is pretty standard for things that don't support oauth or mtls.

**Comment by pratik322** [comment]
I mean to say if we uses **ignore_ssl: False** instead of true where to keep the certificates and make sure it uses the SSL properly? Can you please help.

**Comment by pratik322** [comment]
I'm using  ignore_ssl: False in the VMware configuration file.

**Comment by pryorda** [comment]
@pratik322 If you're hoping it would use mtls based auth, that is not implemented.  typically certs are stored in the /etc/ssl or ca-certificates directory and you would need to run the hook to have it add them to the correct places.
