### ISSUE TITLE
Connect to vcenter through Proxy

### ISSUE THREAD

**Issue by xenofree** [pryorda/vmware_exporter#268]
Hi,

I have to go through a proxy to connect to my vcenter.
The pyvim.connect don't seems to handle that.

Is it possible to connect with pyvim.SmartStubAdapter ? Don't really know if it does the same thing.

**Comment by pryorda** [comment]
Closing for now. We can reopen in the future if people still want this.

**Comment by poblin-orange** [comment]
Hello guys. This would really be usefull. I thought just setting https_proxy env var could be enough but doesnt seem so ...
Any suggestion ?
