### ISSUE TITLE
I have some question related to average metrics.

### ISSUE THREAD

**Issue by get206** [pryorda/vmware_exporter#269]
Hi, Thanks for your sharing good exporter.
I'm trying to monitor all of my vsphere infra with your exporter and I have some question about average metrics.

Typically the average metrics are based on percentage(%). 
However the average values with vmware_exporter shown me that not a percentage.

For example, there are two memory latency metrics on exporter and powercli.
The one thing on exporter is 'vmware_host_memory_latency_metric', and the other thing on powercli is 'mem.latency.average'.

'mem.latency.average' completely shown the percentage value but 'vmware_host_memory_latency_average' is not.

Please let me know about the exactly mean of average.

**Comment by pryorda** [comment]
A good place to start is https://www.vmware.com/support/developer/converter-sdk/conv61_apireference/vim.PerformanceManager.html. 

Let me know if you have further questions and repon this ticket.
