### ISSUE TITLE
Custom scrapping port

### ISSUE THREAD

**Issue by Outek** [pryorda/vmware_exporter#270]
Hi

It would be nice, if we can change the scraping port for prometheus with a variable. 
We already using Prometheus and have configured firewall rules for the scraping tcp/9182. So it would be nice, if we can use the same port.
Maybe something like this:
```txt
LISTEN_PORT='9182'

or

SCRAPE_PORT='9182'
```

**Comment by pryorda** [comment]
Updating your start command to vmware_exporter.py --port 9182

**Comment by Outek** [comment]
I'm using your docker container.
So i have to build my own image i guess.

**Comment by pryorda** [comment]
Nah. How are you running it currently? What are the attributes etc? you should just be able to add command args since the entrypoint is vmware_exporter already or just mapp the port like so. 


docker run -d --rm -e MY_ENV_VARS -p 9182:9272 pryorda/vmware_exporter

**Comment by Outek** [comment]
Ok, thank you for the support, this did the trick. Second problem was the i already used the same port with another exporter.

**Comment by pryorda** [comment]
Whoops. Glad you worked it out.
