### ISSUE TITLE
RancherOS Disk Metrics

### ISSUE THREAD

**Issue by gprakosa** [pryorda/vmware_exporter#285]
Hi @pryorda,

Seems like disk metrics reported for [RancherOS](https://github.com/rancher/os) is recurring for each partitions, as below 

![grafana](https://user-images.githubusercontent.com/6815935/129506360-d74d4571-3364-4106-820d-1d38eecb868b.png)

while actually in vsphere client is matches with only once

![vsphere-client](https://user-images.githubusercontent.com/6815935/129506253-57fdbbc1-b863-4b08-9d53-0bb899e3af36.png)

Thanks,

**Comment by pryorda** [comment]
You can have prometheus scrape filter certain metrics and filesystems. I'd suggest using that approach.
