### ISSUE TITLE
Docker release missing for 0.17.1

### ISSUE THREAD

**Issue by skorpy2009** [pryorda/vmware_exporter#286]
Hey there,

Sadly there is no docker release for version 0.17.0 or 0.17.1
Are they not automated?
https://hub.docker.com/r/pryorda/vmware_exporter/tags?page=1&ordering=last_updated

**Comment by pryorda** [comment]
Thank you for pointing this out. Looks like docker hub is forcing you to use a pro plan for automation based on tags. Ill see what actions are already developed for this and get it added.

**Comment by pryorda** [comment]
Should be fixed with #293
