### ISSUE TITLE
vmware.rules.yml

### ISSUE THREAD

**Issue by medeirosjrm** [pryorda/vmware_exporter#289]
Good afternoon,

I'm having a lot of difficulty creating alerts, does anyone have example alerts for vmware, vmware_datastore_freespace_size, vmware_host_connection_state down

Thank you very much 
wait
Ricardo

**Comment by pryorda** [comment]
Have you looked at https://github.com/pryorda/vmware_exporter/blob/main/alerts/vmware.rules.yml?
