### ISSUE TITLE
Not able to scrape other than Default

### ISSUE THREAD

**Issue by safadig** [pryorda/vmware_exporter#304]
Config.yml has 2 vcenter, the default and then a second one that I called vcenter2 ( tried also calling esx)

Running command:
 `vmware_exporter -c /etc/alertmanager/config.yml`

shows scraping ends at default collection

**Comment by gonzalez** [comment]
@safadig 
Can you try curl http://localhost:9272/?section=vcenter2 from the host running vmware_exporter. ?|
This will trigger a scape of vcenter2.

**Comment by pryorda** [comment]
@gonzalez Thanks for helping out here. Going to close this out as that is the solution in this case.
