### ISSUE TITLE
label values are getting switched

### ISSUE THREAD

**Issue by robasp** [pryorda/vmware_exporter#321]
Hello

I have been experiencing the following issue for all vmware_vm_* metrics:
Example:

![image](https://user-images.githubusercontent.com/105059474/175980023-addc24bc-1158-437e-af44-b46080057408.png)

In Grafana, i see gaps in vmware_vm_snapshot_timestamp_seconds.
It appears as if there were 2 Snaphots on "vm1", one named "snapshot1" and one named "Debian 8".
However, in vCenter vm1 only has 1 snapshot (snapshot1) and "Debian 8" is the value of a custom attribute called OS_Version. The values are switched, creating two separate timeseries instead of one.

The fields "Contact" and abc_information are also changed somehow (see "Foo" & "Bar")

Does someone have an idea why this is happening?

Thanks and kind regards

**Comment by ApocBoots** [comment]
This is probably related to #295

**Comment by robasp** [comment]
setting **fetch_tags: False** fixed the issue for me.

**Comment by gberche-orange** [comment]
Observed the same problem with v0.18.3 where vm metrics labels where mixed up, and not exactly matching vm tags.
