### ISSUE TITLE
same config.yml work on vmware_exporter script but not on dockerized vmware_exporter

### ISSUE THREAD

**Issue by pito2808** [pryorda/vmware_exporter#326]
hi,

here are my setup:
Operating System: Ubuntu 20.04.3 LTS
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
vmware_expoerter 0.18.3 ( pip )
i have installed a vmware_exporter using pip and started with this config file :
default:
    vsphere_host: "XXXXXXX"
    vsphere_user: "XXXXXXX"
    vsphere_password: "XXXXXXXX"
    ignore_ssl: True
    specs_size: 5000
    fetch_custom_attributes: True
    fetch_tags: True
    fetch_alarms: True
    collect_only:
        vms: False
        vmguests: False
        datastores: False
        hosts: True
        snapshots: False

AAAA-vc001v:
    vsphere_host: "XXXX"
    vsphere_user: 'XXXXXXX'
    vsphere_password: 'XXXXX'
    ignore_ssl: True
    specs_size: 5000
    fetch_custom_attributes: True
    fetch_tags: True
    fetch_alarms: True
    collect_only:
        vms: False
        vmguests: False
        datastores: False
        hosts: True
        snapshots: False
BBBB-vc001v:
    vsphere_host: XXXXX
    vsphere_user: 'XXXXX'
    vsphere_password: 'XXXXXX'
    ignore_ssl: True
    specs_size: 5000
    fetch_custom_attributes: True
    fetch_tags: True
    fetch_alarms: False
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: True

CCCC-vc001v:
    vsphere_host: XXXXXXXX
    vsphere_user: 'XXXXXX'
    vsphere_password: 'XXXXXXXX'
    ignore_ssl: True
    specs_size: 5000
    fetch_custom_attributes: True
    fetch_tags: True
    fetch_alarms: False
    collect_only:
        vms: False
        vmguests: False
        datastores: False
        hosts: True
        snapshots: False

i start the exporter with this command :
vmware_exporter -c ./config.yml

it runs fine . i'm able to get each section from browser : http://XXXX:9272/metrics?section=AAAA-vc001v or from prometheus.

Using the same config  using dockerized vmware_exporter , it's not able to find my section: 

starting with this command : 
docker run -it --rm -p 9272:9272 --name vmware_exporter --network=host -v /home/igc5616/workspace/vmware_exporter/config.yml:/opt/vmware_exporter/config.yml pryorda/vmware_exporter

it got this error message when i try to reach the section: 
WARNING: Published ports are discarded when using host network mode
2022-07-25 09:52:59,111 INFO:Starting web server on port :9272
2022-07-25 09:54:31,983 INFO:AAAA-vc001v is not a valid section, using default
2022-07-25 09:54:31,983 INFO:No vsphere_host or target defined

when i validate the config.yml on docker's container shell:

(vmware_exporter_env) igc5616@gtnbs-mn501v:~/workspace/vmware_exporter$ sudo docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS         PORTS     NAMES
683ee702473d   pryorda/vmware_exporter            "/usr/local/bin/vmwa…"   3 minutes ago   Up 3 minutes             vmware_exporter
a3c7fb886b6f   grafana/grafana-enterprise:8.5.0   "/run.sh"                3 days ago      Up 3 days                pensive_lovelace
df64dd88de28   prom/prometheus                    "/bin/prometheus --c…"   6 days ago      Up 4 days                affectionate_bouman
(vmware_exporter_env) igc5616@gtnbs-mn501v:~/workspace/vmware_exporter$ sudo docker exec -it 683ee702473d sh

/opt/vmware_exporter # ls
CHANGELOG.md              README.md                 config.yml                openshift                 setup.py                  vmware_exporter
Dockerfile                alerts                    dashboards                requirements-tests.txt    systemd                   vmware_exporter.egg-info
LICENSE                   build                     docker-compose.yml        requirements.txt          tests
MANIFEST.in               catalog-info.yaml         kubernetes                setup.cfg                 validate-signature.rb
/opt/vmware_exporter # cat config.yml
default:
    vsphere_host: "XXXXXX"
    vsphere_user: "XXXXXXX"
    vsphere_password: "XXXXXXX"
    ignore_ssl: True
    specs_size: 5000
    fetch_custom_attributes: True
    fetch_tags: True
    fetch_alarms: True
    collect_only:
        vms: False
        vmguests: False
        datastores: False
        hosts: True
        snapshots: False

AAAAA-vc001v:
    vsphere_host: "gtnbs-vc001v"
    vsphere_user: "XXXXXX"
    vsphere_password: "XXXXXXX"
    ignore_ssl: True
    specs_size: 5000

--- CUT---

it shows config file is the same but SECTION is not reckonized with dockerized vmware_exporter.
any help or clue will be welcome !

regards,

georges

**Comment by thuvh** [comment]
it's run command with `config_file=None` and all config is loaded from environments, you can read [configure function](https://github.com/pryorda/vmware_exporter/blob/f32eaa902fabb0cc084b8801f427faed4b84a936/vmware_exporter/vmware_exporter.py#L1870) and [AAAA-vc001v is not a valid section, using default](https://github.com/pryorda/vmware_exporter/blob/f32eaa902fabb0cc084b8801f427faed4b84a936/vmware_exporter/vmware_exporter.py#L1953). Message [No vsphere_host or target defined](https://github.com/pryorda/vmware_exporter/blob/f32eaa902fabb0cc084b8801f427faed4b84a936/vmware_exporter/vmware_exporter.py#L1964) appeared because no environment [`VSPHERE_HOST`](https://github.com/pryorda/vmware_exporter/blob/f32eaa902fabb0cc084b8801f427faed4b84a936/vmware_exporter/vmware_exporter.py#L1885).

So:
1. you can use docker compose as example
2. or start container with command `docker run ... /usr/local/bin/vmware_exporter -c /opt/vmware_exporter/config.yml`

**Comment by pito2808** [comment]
hi,

thanks. it works . it's because of my inexperience with docker  :)
