### ISSUE TITLE
Metrics definition

### ISSUE THREAD

**Issue by pritam27** [pryorda/vmware_exporter#330]
@pryorda 
Hi! Where can I find the definition of all metrics provided by vmware exporter? For example what is the difference between the following cpu usage metrics?
vmware_host_cpu_usage_average
vmware_host_cpu_usage
vmware_host_cpu_usagemhz_average
vmware_host_cpu_used_summation

**Comment by thuvh** [comment]
You can find these metrics from [here](https://github.com/pryorda/vmware_exporter/blob/f32eaa902fabb0cc084b8801f427faed4b84a936/vmware_exporter/vmware_exporter.py#L1409), then look the document from vmware

**Comment by pritam27** [comment]
Thank you very much.
