### ISSUE TITLE
add -c config.yml How to exchange command in Docker-compose ?

### ISSUE THREAD

**Issue by gerrard2030** [pryorda/vmware_exporter#332]
add -c config.yml How to exchange command in Docker-compose ?

**Comment by M0NsTeRRR** [comment]
Hello,

You can pass it to `command` in your docker-compose.yml as the documentation say https://docs.docker.com/compose/compose-file/compose-file-v3/#command

Like :
```yaml
command: ["-c", "config.yml"]
```

**Comment by alexusbbb** [comment]
Привет
У меня вроде работает так:
```
    command:
      -c /etc/vmware-exporter/config.yml
      -l DEBUG
```
