### ISSUE TITLE
How to get the IP address of the vm, currently it can only be seen in the console of vcenter

### ISSUE THREAD

**Issue by ilanni2460** [pryorda/vmware_exporter#336]
How to get the IP address of the vm, currently it can only be seen in the console of vcenter

**Comment by fuquanyou2017** [comment]
我们研究过获取虚机IP的流程，发现其非常复杂；另外，一台虚机可能存在多块网口、多个IP。该项目可能基于以上原因而没有列出虚机IP吧。

**Comment by ilanni2460** [comment]
@fuquanyou2017 好的，非常感谢

**Comment by tqi-raurora** [comment]
@ilanni2460 
Greetings!
Did you manage to get the IP address?
If so, would you be kind enough to share how you did it?

**Comment by tqi-raurora** [comment]
Maybe this will help someone, we had the same need and created a fork for this.
I created a PR here: https://github.com/pryorda/vmware_exporter/pull/357
