### ISSUE TITLE
'AttributeError' object has no attribute 'message'

### ISSUE THREAD

**Issue by ArabianCat** [pryorda/vmware_exporter#348]
Hi,
I'm in Debian, and when I run vmware_export -c config.yml, an error appear (look the screen).
Can you know why ?
Cordially,

![image](https://user-images.githubusercontent.com/102919110/208134249-eefe5796-5b2f-4df8-af23-f3a0e376a31c.png)

**Comment by iceman91176** [comment]
Hi @ArabianCat, 
it seems that your configuration-file is invalid/incomplete.
Could you provide the contents ?
Thank you

**Comment by ArabianCat** [comment]
Hi, yeah it's that, sorry.
