### ISSUE TITLE
needs pyopenssl

### ISSUE THREAD

**Issue by grinapo** [pryorda/vmware_exporter#356]
Seems like this needs pyopenssl (23.0.0 here, maybe older will do), but requirements didn't pull it up. Had to be installed manually.

**Comment by pryorda** [comment]
@M0NsTeRRR Thanks for responding here. @grinapo Our supported method is using docker/kube/helm. Can you explain what you are running into?

**Comment by M0NsTeRRR** [comment]
Your welcome @pryorda,
I've mentionned SSO because pyvomi as an extra argument for SSO that pull pyopenssl

**Comment by grinapo** [comment]
I do not use SSO or k8s. :-) 
And right now I'm not using vmware either, so it's okay if you close that. Just wanted to ping you in case you see something trivial to fix. Thanks for responding!
