### ISSUE TITLE
Should not be installed directly on VCenter7

### ISSUE THREAD

**Issue by VictorB89** [pryorda/vmware_exporter#361]
Hello,

Should warn on the readme that it should not be installed directly on Vcenter 7, because internal process vmware-rhttpproxy won't work anymore since your installer overwrite the pyvmomi library.
Will break your Vcenter.

**Comment by ShmoeTheHo** [comment]
There was a modicum of 'assumed knowledge' here that most people know better than to install pretty much anything on a managed appliance.
