### ISSUE TITLE
Problems starting exporter

### ISSUE THREAD

**Issue by VR6Pete** [pryorda/vmware_exporter#37]
Hi All,

Having a few issues starting the exporter;

ubuntu@ukasprom02:~/vmware_exporter-0.6.4/vmware_exporter$ vmware_exporter -c /home/ubuntu/vmware_exporter-0.6.4/vmware_exporter/config.yml
Traceback (most recent call last):
  File "/usr/local/bin/vmware_exporter", line 11, in <module>
    load_entry_point('vmware-exporter==0.6.4', 'console_scripts', 'vmware_exporter')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/vmware_exporter-0.6.4-py2.7.egg/vmware_exporter/vmware_exporter.py", line 206

config.yml
default:
    vsphere_host: "xxxxxx"
    vsphere_user: "xxxxx"
    vsphere_password: "xxxxxx"
    ignore_ssl: True
    collect_only:
        vms: False
        vmguests: False
        datastores: True
        hosts: True
        snapshots: False

any idea what could be causing this?

Cheers

Pete

**Comment by pryorda** [comment]
Still having issues @VR6pete?

**Comment by VR6Pete** [comment]
Oh sorry this slipped my mind. Will take a look tomorrow.

**Comment by VR6Pete** [comment]
Hi there,

I've updated my original post with the error now ive updated to the latest release, different error this time, and have also posted up my config.

Python 2.7.15rc1

**Comment by Jc2k** [comment]
That’s a weird error - it’s not even getting into our code.

It might be worth trying python 3, which is what the Docker setup uses. I don’t know if any of us use python 2, and we only have CI for py 3.

**Comment by VR6Pete** [comment]
Ok, have tried with py3 and now get different error :) 

ubuntu@ukasprom02:~/vmware_exporter-0.6.4/vmware_exporter$ python3 vmware_exporter.py -c /home/ubuntu/vmware_exporter-0.6.4/vmware_exporter/config.yml
Traceback (most recent call last):
  File "vmware_exporter.py", line 34, in <module>
    from .helpers import batch_fetch_properties
ModuleNotFoundError: No module named '__main__.helpers'; '__main__' is not a package

I am not running inside docker, is there a list of pre-req modules etc... I should install?

**Comment by VR6Pete** [comment]
nstalling collected packages: prometheus-client, pytz, six, urllib3, certifi, chardet, idna, requests, pyvmomi, setuptools, PyHamcrest, zope.interface, hyperlink, attrs, Automat, incremental, constantly, twisted, PyYAML, yamlconfig, pyasn1, pyasn1-modules, enum34, asn1crypto, pycparser, cffi, ipaddress, cryptography, service-identity, vmware-exporter
Successfully installed Automat-0.7.0 PyHamcrest-1.9.0 PyYAML-3.13 asn1crypto-0.24.0 attrs-18.2.0 certifi-2018.11.29 cffi-1.11.5 chardet-3.0.4 constantly-15.1.0 cryptography-2.4.2 enum34-1.1.6 hyperlink-18.0.0 idna-2.8 incremental-17.5.0 ipaddress-1.0.22 prometheus-client-0.5.0 pyasn1-0.4.5 pyasn1-modules-0.2.3 pycparser-2.19 pytz-2018.9 pyvmomi-6.7.1.2018.12 requests-2.21.0 service-identity-18.1.0 setuptools-40.6.3 six-1.12.0 twisted-18.9.0 urllib3-1.24.1 vmware-exporter-0.6.4 yamlconfig-0.3.1 zope.interface-4.6.0
Segmentation fault (core dumped)

**Comment by Jc2k** [comment]
So the first error message is because of the way you are invoking things. If you directly run the python script like that the PYTHONPATH isn't set up correctly. You have a couple of choices when running from a git checkout:

1 - put '.' (current dir) on the python path:

```
PYTHONPATH=.:$PYTHONPATH python3 vmware_exporter.py
```

2. install it in dev mode:

```
pip install -e .
```

(Only if you are using virtualenv)

If you aren't planning to hack on it the pypi version is fine. If you don't know how to invoke the python 3 version of pip a trick I use is:

```
python3 -m pip install vmware-exporter
```

Then I don't have to worry whether this particular distro has mapped pip or pip3 ro the right version of pip.

I don't know why your pip install is seg faulting! It really shouldn't, the most common for pip failures like that would probably be not enough RAM. But i've never seen that personally.

**Comment by pryorda** [comment]
I honestly don't run the pip install, only the docker container. If you can't get it working using the above commands, I strongly recommend switching to the docker container to run this.

**Comment by VR6Pete** [comment]
working in a docker container now :) Thanks !

**Comment by pryorda** [comment]
Closing for now. Let us know if you experience any other weirdness.
