### ISSUE TITLE
Memory Usage of Virtual Machine graph

### ISSUE THREAD

**Issue by thuvh** [pryorda/vmware_exporter#374]
Hello @pryorda 
I have a question about ```vmware_vm_memory_usage_average```, 
In the configuration of grafan dashboard, the query to draw memory usage in percentage is ```"expr": "(vmware_vm_mem_usage_average{vm_name=~\"$vm\"}) * 100 / (vmware_vm_memory_max{vm_name=~\"$vm\"})",```. But I check from [this](https://communities.vmware.com/t5/VMware-PowerCLI-Discussions/Mem-Usage-Average-against-the-total-aggregate-of-cluster-host/td-p/396033), [this](https://www.virten.net/2023/01/vsphere-8-0-performance-counter-description/), and more, they told that `vmware_vm_memory_usage` is in percentage, so why we need to div to `vmware_vm_memory_max`?

**Comment by pryorda** [comment]
It seems like this is attempt at converting it back to MB since vmware_vm_memory_max is summary.config.memorysizemb. You could probably use the second half and just compart it to the usuage average in the perf monitor to see if its accurate.

**Comment by thuvh** [comment]
Thank you!
