### ISSUE TITLE
Using vmware_exporter in Linux

### ISSUE THREAD

**Issue by BHAARATH002** [pryorda/vmware_exporter#384]
Hi,

I'm planning to use this in a Linux instance but i'm not sure on the setup.
Is there any setup guide for using the exporter in Linux?
I'm planning use the vmware_exporter to send the data prometheus using grafana-agent.
This is my instance: Red Hat Enterprise Linux release 9.2 (Plow)

`
vi /usr/lib/systemd/system/vmware_exporter.service

[Unit]
Description=Prometheus VMWare Exporter
After=network.target

[Service]
User=root
WorkingDirectory=/opt/xxxxxx/vmware-exporter/vmware_exporter-0.18.4/vmware_exporter
ExecStart=/opt/xxxxx/vmware-exporter/vmware_exporter-0.18.4/vmware_exporter/vmware_exporter.py
Type=simple

[Install]
WantedBy=multi-user.target

vi /opt/xxxxx/vmware-exporter/vmware_exporter-0.18.4/vmware_exporter/config.yml

default:
  vsphere_host: "https://xxxxxxx.xxxxxx.com/sdk"
  vsphere_user: "xxxxxxx"
  vsphere_password: "xxxxxxx"
  ignore_ssl: True
  collect_only:
      vms: False
      vmguests: False
      datastores: True
      hosts: True
      snapshots: False
`

Getting the following error:
Oct 19 07:54:08 sgnt-dev-graf01.illumina.com systemd[1]: Started Prometheus VMWare Exporter.
Oct 19 07:54:09 sgnt-dev-graf01.illumina.com vmware_exporter.py[123858]: Traceback (most recent call last):
Oct 19 07:54:09 sgnt-dev-graf01.illumina.com vmware_exporter.py[123858]:   File "/opt/illumina/vmware-exporter/vmware_exporter-0.18.4/vmware_exporter/vmware_exporter.py", line 49, in <module>
Oct 19 07:54:09 sgnt-dev-graf01.illumina.com vmware_exporter.py[123858]:     from .helpers import batch_fetch_properties, get_bool_env
Oct 19 07:54:09 sgnt-dev-graf01.illumina.com vmware_exporter.py[123858]: ImportError: attempted relative import with no known parent package
Oct 19 07:54:09 sgnt-dev-graf01.illumina.com systemd[1]: vmware_exporter.service: Main process exited, code=exited, status=1/FAILURE
Oct 19 07:54:09 sgnt-dev-graf01.illumina.com systemd[1]: vmware_exporter.service: Failed with result 'exit-code'.

**Comment by BHAARATH002** [comment]
I managed to resolve it using this https://github.com/pryorda/vmware_exporter/issues/122#issuecomment-770620932 solution. But now i'm not able to run the grafana-agent to scrap the vmware-exporter.
agent-config.yml
`
server:
  log_level: debug

metrics:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 15s
    remote_write:
      - url: xxxxxxx
        basic_auth:
          username: xxxxxxx
          password: xxxxxxx
        queue_config:
          max_samples_per_send: 5000
          max_shards: 500
          capacity: 5000
          retry_on_http_429: true
          max_backoff: 10s
          min_backoff: 1s
          batch_send_deadline: 25s
  configs:
  - name: default
    host_filter: false
    scrape_configs:
      - job_name: 'vmware_vcenter'
          metrics_path: /metrics
          static_configs:
          - targets:
            - 'https://xxxx.xxxxx.com/sdk'
          relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: exporter_ip:9272
`

**Comment by pryorda** [comment]
Ive never used the graphana agent so I can not assist here.
