### ISSUE TITLE
Add "cluster" label for hosts, vms and datastores

### ISSUE THREAD

**Issue by pryorda** [pryorda/vmware_exporter#4]
_From @dannyk81 on February 9, 2018 22:35_

It would be great to add "cluster" label to indicate to which HA cluster the host/vm belongs to.

Same, for datastores that belong to a Datastore cluster.

We manage multiple clusters with the same vCenter, and would like to filter metrics per "PROD" and "STAGING" clusters, for example.

_Copied from original issue: rverchere/vmware_exporter#28_

**Comment by dannyk81** [comment]
Hey @pryorda! I've seen to have missed you taking over, apologies!

I'm going to try and prepare a PR to add this into your variant, may take me some time as I see quite a bit has changed.
