### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by pryorda** [pryorda/vmware_exporter#47]
As a vmware_exporter dev, I believe that it would be best to have unit tests for all of the code. This will allow us to test changes rapidly, enable true CI, and not be as worried when pushing new changes.

This should go in after #44 and will freeze this project to changes until they are done.

@dannyk81 @jc2k Thoughts?

**Comment by dannyk81** [comment]
+💯 on this

I suppose we'll need to check if there's any decent/up-to-date mocking framework available.

**Comment by pryorda** [comment]
Yeah, I'm not well versed in the python unittest stuff. If you guys have any recommendations, I will not have any preference.

**Comment by Jc2k** [comment]
Normally I’d use py.test and the built in python 3 unittest.mock.

The biggest problem will be the pyvmomi objects are fairly magic, I’m a bit worried about creating adequate fakes for them. But I think bad ones would be better than the current situation.

We could do some integration tests on the Docker container itself with https://pypi.org/project/pytest-docker-tools/ (disclaimer - I wrote it). Just a high level test of the healthz endpoint would be enough to catch some of the problems we had with python path recently. I normally run those tests on gitlab but I think I self test pytest-docker-tools on travis-ci.

**Comment by Jc2k** [comment]
I could probably put together a candidate PR for travis ci + some py.test tests from one of my other projects if no one has any strong preferences.

**Comment by pryorda** [comment]
#50
