### ISSUE TITLE
Create Chat Place

### ISSUE THREAD

**Issue by pryorda** [pryorda/vmware_exporter#48]
We need to have a place where we can have instant chat without jumping between tickets.

**Comment by dannyk81** [comment]
How about https://gitter.im/? should be easy to setup and it uses your GitHub persona.

**Comment by dannyk81** [comment]
You can auto-create a community linking to the project and it even creates a PR to add a badge to join the chat 😄 

![image](https://user-images.githubusercontent.com/24274156/50494367-d1e8b280-09f0-11e9-9c8c-890468f82164.png)

If you like it, I can set it up.
