### ISSUE TITLE
Add VM metric to indicate vm tools status

### ISSUE THREAD

**Issue by dannyk81** [pryorda/vmware_exporter#71]
This will be very helpful to ensure vmtools is running on all VMs as required, perhaps we can even include the version.

We're actually hitting an issue form time to time where our terraform plan/apply stalls because some vmtools crashed on some VMs and it's a bit tricky to hunt down which one(s), this would make our lives much easier.

an example is available [here](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/list_vmwaretools_status.py)

I'll try to prepare a PR for this (if no objections), once we move forward with the more heavier changes in the pipe.

**Comment by pryorda** [comment]
👍 ✨ I think this would be good to have and maybe we can grab it with propertycollector too?

**Comment by pryorda** [comment]
I'm not sure PropertyCollector could do it, but these show that its in the summary. 

https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.vm.GuestInfo.html#toolsRunningStatus
https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.vm.Summary.GuestSummary.html#toolsRunningStatus

**Comment by dannyk81** [comment]
not sure why prop collector won't work, these are the properties we need to need (from the example I linked in the issue description):
```
vm.guest.toolsRunningStatus,
vm.guest.toolsVersion,
vm.guest.toolsVersionStatus2
```

we already collect `vm.guest."` properties and seems to work just fine

**Comment by Jc2k** [comment]
It’s definitely worth trying - from what you’ve said I’d expect it to work, possibly with the values being missing from the results if guest tools not installed, but we already deal with that sort of stuff.
