### ISSUE TITLE
Docker image - multiple vsphere environments 

### ISSUE THREAD

**Issue by VR6Pete** [pryorda/vmware_exporter#83]
Hi. 

Using the docker image and using the example command line in the from the readme. This is working great however I have 2 platforms that I’d wish to collect metrics from. 

What is the best practice for this requirement using this exporter ? 

Cheers. 

Pete

**Comment by VR6Pete** [comment]
How am I calling that config file when using docker? Sorry but didn’t seem overly obvious in the read me 👍🏻

**Comment by dannyk81** [comment]
With docker, you usually bind mount the config file from the host.

example:
```
$ docker run -p 9272:9272 -v /etc/vmware-exporter:/etc/vmware-exporter/ \
        --name vmware-exporter \
        <vmware-exporter-image> \
         -c /etc/vmware-exporter/config.yml
```

Above assumes: your host as a directory `/etc/vmware-exporter` with the config file called `config.yml`

**Comment by pryorda** [comment]
use ?section= instead

**Comment by pryorda** [comment]
Also if you are interested in the logic around this:

https://github.com/pryorda/vmware_exporter/blob/master/vmware_exporter/vmware_exporter.py#L793

**Comment by VR6Pete** [comment]
awesome, that has helped a lot and now getting some metrics back.

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 777, in _async_render_GET
    request.write(b'# Collection failed')
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 238, in write
    http.Request.write(self, data)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1137, in write
    self.channel.writeSequence(toChunk(data))
builtins.AttributeError: 'NoneType' object has no attribute 'writeSequence'

Getting this error in the logs though now - note running old version of vsphere 5.1 (will be upgraded to 6.7 in coming weeks)

**Comment by Jc2k** [comment]
That’s normally if the connection drops before it finishes collecting metrics or writing to the socket - there is a bug open for hiding that error (it’s harmless) but you might need to raise your Prometheus timeout - the esx APIs are slowwswww.

**Comment by VR6Pete** [comment]
this was just loading the exporter /metrics output - prometheus not in play just yet :)

more error output;

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [<prometheus_client.core.GaugeMetricFamily object at 0x7f46452510b8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251908>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251b38>, <prometheus_client.core.GaugeMetricFamily object at 0x7f46452519e8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251550>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251a90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f46452515f8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251e48>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251cc0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f46452519b0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f46452512e8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251320>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251048>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251cf8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f46452514a8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251a20>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251ac8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251588>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251470>, <prometheus_client.core.GaugeMetricFamily object at 0x7f4645251160>]

**Comment by pryorda** [comment]
Did you refresh while it was loading or switch urls?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by VR6Pete** [comment]
not that I recall, Just an FYI really, it did return the metrics just observed that in the logs.

**Comment by pryorda** [comment]
That's actually a bug in twisted around connection handling. They are working on it.

**Comment by cherryroy** [comment]
Hello All, I have similar issue and I am not running docker, just using a VM to host my exporter and wanting to add more than 1(around 9) vcenters to this exporter. I made changes to the config.yml, but how do I make changes to config.env on main vmware_exporter directory? i would appreciate if someone can lay out the steps for multiple vcenters.
