### ISSUE TITLE
python2 support

### ISSUE THREAD

**Issue by arno01** [pryorda/vmware_exporter#84]
vmware-exporter 0.6.5 gets a syntax error whenever I am trying to use python2:

```
# vmware_exporter -c /etc/default/vmware_exporter.yml 
Traceback (most recent call last):
  File "/usr/local/bin/vmware_exporter", line 7, in <module>
    from vmware_exporter.vmware_exporter import main
  File "/usr/local/lib/python2.7/dist-packages/vmware_exporter/vmware_exporter.py", line 206
    return list(metrics.values())   # noqa: F705
SyntaxError: 'return' with argument inside generator
```

https://github.com/pryorda/vmware_exporter/blob/ccdf5e9/vmware_exporter/vmware_exporter.py#L206

I found here https://www.pythondoeswhat.com/2017/04/a-return-to-yield_29.html they suggest using python3.
Nevertheless, I am wondering whether python2 will be supported or dropped?

Thank you.

**Comment by dannyk81** [comment]
We use and test the exporter against Python3, not sure it will work with Python2.

@Jc2k wdyt?

**Comment by pryorda** [comment]
We are dropping python2 support.

**Comment by Linuxmatrix** [comment]
i'm getting same but i'm using python 3 
can any one have solution for this issue  


root@prometheus-virtual-machine:~#  vmware_exporter -c config.ym
Traceback (most recent call last):
  File "/usr/local/bin/vmware_exporter", line 7, in <module>
    from vmware_exporter.vmware_exporter import main
  File "/usr/local/lib/python2.7/dist-packages/vmware_exporter/vmware_exporter.py", line 305
    return list(metrics.values())   # noqa: F705
SyntaxError: 'return' with argument inside generator

**Comment by Jc2k** [comment]
You aren't actually using python 3, look:

```
  File "/usr/local/lib/python2.7/dist-packages/vmware_exporter/vmware_exporter.py", line 305
```

It's installed as a python 2.7 package.

BTW, It's generalyl frowned upon to comment on issues that have been close for over a year.
