### ISSUE TITLE
getting errors while trying to collect data and scaling

### ISSUE THREAD

**Issue by AmirShalom** [pryorda/vmware_exporter#98]
Hi,
I'm getting this errors while running the vmware_exporter container:

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 421, in host_labels
    result = yield threads.deferToThread(lambda: _collect(dc, dc.hostFolder))
  File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 421, in <lambda>
    result = yield threads.deferToThread(lambda: _collect(dc, dc.hostFolder))
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 414, in _collect
    host_inventory.extend(_collect(dc, folder))
builtins.AttributeError: 'dict' object has no attribute 'extend'

This is the relevant part in the docker-compose file:

  vmware_exporter:
    image: pryorda/vmware_exporter:latest
    restart: always
    links:
      - prometheus
    ports:
      - "9272:9272"
    environment:
        VSPHERE_HOST: 'VCenter.domain.com'
        VSPHERE_USER: 'user'
        VSPHERE_PASSWORD: 'password'
        VSPHERE_IGNORE_SSL: 'True'
        VSPHERE_COLLECT_VMS: 'False'
        VSPHERE_COLLECT_VMGUESTS: 'False'
        VSPHERE_COLLECT_DATASTORES: 'False'
        VSPHERE_COLLECT_SNAPSHOTS: 'False'
        VSPHERE_COLLECT_HOSTS: 'True'

I'm using VSphere 6.

what am I doing wrong? (as you can see I'm using the latest version).

thank you

**Comment by pryorda** [comment]
Hopefully I dont have to revert my changes yesterday. When did you do a docker pull last and what version of 6? Also, what does the folder structure look like?

**Comment by AmirShalom** [comment]
Hi,
Thank you for the quick response, apparently, the scraping time is very high and I got errors from previous runs. I'm not getting this error anymore.
It takes about ~40 minutes and I'm checking it in the VSphere (6.0) server.

**Comment by dannyk81** [comment]
wow! 40 minutes? I assume you meant 40 seconds :sweat_smile: 

In any case, it's quite a lot... our largest deployment has about 30 ESXi nodes, 27 datastores and ~500 VMs, takes ~3 seconds to scrape.

Can you share some details about your environment?

**Comment by AmirShalom** [comment]
Unfortunately, I meant minutes  haha. 
The environment specs are: ~12,000 VMs, 180 ESX's and about 300 datastores, which is big but the scrapping time is way too much.
I'm checking the long duration scrapping time in two ways:
- Memory allocation for the VCenter services is maybe not ideal - Checking if it is needed to change the "-Xmx" argument which specifies the hard memory limitation for each process separately.
- Maybe there is a limitation for the API requests to the vcenter server which we exceeded.

I will let you know about the results of our check.
I'm open to hear any suggestions you have.

**Comment by pryorda** [comment]
@AmirShalom you have all of that under one DC?

**Comment by AmirShalom** [comment]
I'm running ~12,000 VMs , 180 ESX's and about 300 DS's under one DC. After changing the memory size for a few java services in the VSphere server the scraping time is about 2 minutes and 30 seconds (vmware_exporter is already improving my environment :) ). 
I noticed that I get metrics that related to the VMs or to the guest OS as such as:
"vmware_vm_power_state" , "vmware_vm_num_cpu" , "vmware_vm_guest_tools_version_status" etc'.
I believe this is making the scrape duration longer.
This is happening although I disabled this scraping options, my docker-compose relevant part:

  vmware_exporter:
    image: pryorda/vmware_exporter:v0.7.4
    restart: always
    links:
      - prometheus
    ports:
      - "9272:9272"
    environment:
        VSPHERE_HOST: 'server.domain'
        VSPHERE_USER: 'user'
        VSPHERE_PASSWORD: 'password'
        VSPHERE_IGNORE_SSL: 'True'
        VSPHERE_COLLECT_VMS: 'False'
        VSPHERE_COLLECT_VMGUESTS: 'False'
        VSPHERE_COLLECT_DATASTORES: 'False'
        VSPHERE_COLLECT_SNAPSHOTS: 'False'
        VSPHERE_COLLECT_HOSTS: 'True'

**Comment by pryorda** [comment]
After testing with more vms. I think that I'm going to close this. I'm not sure we can make this faster without major rework currently
